//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActasEntrega
    {
        public int idActaEntrega { get; set; }
        public string numeroFolio { get; set; }
        public int encargado { get; set; }
        public Nullable<int> testigo { get; set; }
        public int supervisor { get; set; }
        public System.DateTime fechaHora { get; set; }
        public Nullable<int> razonSocial { get; set; }
        public int recibe { get; set; }
        public int tipoActa { get; set; }
        public Nullable<int> tipoTestigo { get; set; }
        public int estado { get; set; }
        public string consecutivoActa { get; set; }
        public string inventarioEntregado { get; set; }
    
        public virtual Policias Policias { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        public virtual Policias Policias1 { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
    }
}
