//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActasDecomiso
    {
        public int idActaDecomiso { get; set; }
        public string numeroFolio { get; set; }
        public int oficialActuante { get; set; }
        public int oficialAcompanante { get; set; }
        public int supervisorDecomiso { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombreDecomisado { get; set; }
        public string numeroDeIdentificacionDecomisado { get; set; }
        public string telefonoDecomisado { get; set; }
        public int estadoCivilDecomisado { get; set; }
        public string direccionDecomisado { get; set; }
        public string lugarProcedimiento { get; set; }
        public string inventario { get; set; }
        public string observaciones { get; set; }
    
        public virtual Policias Policias { get; set; }
        public virtual Policias Policias1 { get; set; }
        public virtual Policias Policias2 { get; set; }
    }
}
