//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActasDeObservacionPolicial
    {
        public int idActaDeObservacionPolicial { get; set; }
        public string numeroFolio { get; set; }
        public int oficialActuante { get; set; }
        public int oficialAcompanante { get; set; }
        public int distrito { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idInteresado { get; set; }
        public string condicion { get; set; }
        public string observaciones { get; set; }
        public string direccion { get; set; }
        public int estado { get; set; }
    
        public virtual Policias Policias { get; set; }
        public virtual Policias Policias1 { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
