//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActasDeDestruccionDePerecedero
    {
        public int idActaDeDestruccionDePerecederos { get; set; }
        public string numeroFolio { get; set; }
        public int encargado { get; set; }
        public int testigo { get; set; }
        public int supervisor { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int tipoActaD { get; set; }
        public string consecutivoActa { get; set; }
        public string inventarioDestruido { get; set; }
    
        public virtual Policia Policia { get; set; }
        public virtual Policia Policia1 { get; set; }
        public virtual Policia Policia2 { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
    }
}
