//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armas
    {
        public int idArma { get; set; }
        public Nullable<int> policiaAsignado { get; set; }
        public string numeroSerie { get; set; }
        public int tipoArma { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int calibre { get; set; }
        public int condicion { get; set; }
        public int ubicacion { get; set; }
        public string observacion { get; set; }
        public int estadoArma { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual TablaGeneral TablaGeneral2 { get; set; }
        public virtual TablaGeneral TablaGeneral3 { get; set; }
        public virtual TablaGeneral TablaGeneral4 { get; set; }
    }
}
