//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arma()
        {
            this.Bitacoras = new HashSet<Bitacora>();
        }
    
        public int idArma { get; set; }
        public Nullable<int> policiaAsignado { get; set; }
        public string numeroSerie { get; set; }
        public int tipoArma { get; set; }
        public int marca { get; set; }
        public string modelo { get; set; }
        public int calibre { get; set; }
        public int condicion { get; set; }
        public int ubicacion { get; set; }
        public string observacion { get; set; }
        public int estadoArma { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual TablaGeneral TablaGeneral2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacoras { get; set; }
        public virtual TablaGeneral TablaGeneral3 { get; set; }
        public virtual TablaGeneral TablaGeneral4 { get; set; }
        public virtual TablaGeneral TablaGeneral5 { get; set; }
    }
}
