//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias
    {
        public int idAuditoria { get; set; }
        public int idCategoria { get; set; }
        public int idElemento { get; set; }
        public System.DateTime fecha { get; set; }
        public int accion { get; set; }
        public string justificacion { get; set; }
        public int idUsuario { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
