//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias
    {
        public int idAuditoria { get; set; }
        public int idCategoria { get; set; }
        public int idElemento { get; set; }
        public System.DateTime fecha { get; set; }
        public int accion { get; set; }
        public string justificacion { get; set; }
        public int idUsuario { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
