//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacoras
    {
        public int idBitacora { get; set; }
        public string numeroConsecutivo { get; set; }
        public int idArma { get; set; }
        public int idArmeroProveedor { get; set; }
        public Nullable<int> idArmeroReceptor { get; set; }
        public int idPoliciaSolicitante { get; set; }
        public Nullable<int> condicionFinal { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }
        public string municionEntregada { get; set; }
        public string municionDevuelta { get; set; }
        public string cargadoresEntregados { get; set; }
        public string cargadoresDevueltos { get; set; }
        public string observacionesEntrega { get; set; }
        public string observacionesDevuelta { get; set; }
        public int estadoActualBitacora { get; set; }
    
        public virtual Armas Armas { get; set; }
        public virtual Policias Policias { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Policias Policias1 { get; set; }
    }
}
