//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacoras
    {
        public int idBitacora { get; set; }
        public string numeroConsecutivo { get; set; }
        public int idArma { get; set; }
        public int idArmeroProveedor { get; set; }
        public Nullable<int> idArmeroReceptor { get; set; }
        public int idPoliciaSolicitante { get; set; }
        public int condicionInicial { get; set; }
        public Nullable<int> condicionFinal { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }
        public string municionEntregada { get; set; }
        public string municionDevuelta { get; set; }
        public string cargadoresEntregados { get; set; }
        public string cargadoresDevueltos { get; set; }
        public string observacionesEntrega { get; set; }
        public string observacionesDevuelta { get; set; }
        public int estadoActualBitacora { get; set; }
    
        public virtual Armas Armas { get; set; }
        public virtual Policias Policias { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual Policias Policias1 { get; set; }
    }
}
