//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCAPEntities : DbContext
    {
        public SCAPEntities()
            : base("name=SCAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActasDecomiso> ActasDecomiso { get; set; }
        public virtual DbSet<ActasDeDestruccionDePerecederos> ActasDeDestruccionDePerecederos { get; set; }
        public virtual DbSet<ActasDeNotificacion> ActasDeNotificacion { get; set; }
        public virtual DbSet<ActasDeObservacionPolicial> ActasDeObservacionPolicial { get; set; }
        public virtual DbSet<ActasEntrega> ActasEntrega { get; set; }
        public virtual DbSet<ActasEntregaPorOrdenDe> ActasEntregaPorOrdenDe { get; set; }
        public virtual DbSet<ActasHallazgo> ActasHallazgo { get; set; }
        public virtual DbSet<ActasNotificacionVendedorAmbulante> ActasNotificacionVendedorAmbulante { get; set; }
        public virtual DbSet<Armas> Armas { get; set; }
        public virtual DbSet<Auditorias> Auditorias { get; set; }
        public virtual DbSet<Bitacoras> Bitacoras { get; set; }
        public virtual DbSet<Infractores> Infractores { get; set; }
        public virtual DbSet<PartesPoliciales> PartesPoliciales { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Policias> Policias { get; set; }
        public virtual DbSet<Requisitos> Requisitos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TablaGeneral> TablaGeneral { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
