//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCAPEntities : DbContext
    {
        public SCAPEntities()
            : base("name=SCAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActasDecomiso> ActasDecomisoes { get; set; }
        public virtual DbSet<ActasDeDestruccionDePerecedero> ActasDeDestruccionDePerecederos { get; set; }
        public virtual DbSet<ActasDeObservacionPolicial> ActasDeObservacionPolicials { get; set; }
        public virtual DbSet<ActasEntrega> ActasEntregas { get; set; }
        public virtual DbSet<ActasEntregaPorOrdenDe> ActasEntregaPorOrdenDes { get; set; }
        public virtual DbSet<ActasHallazgo> ActasHallazgoes { get; set; }
        public virtual DbSet<Arma> Armas { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Infractore> Infractores { get; set; }
        public virtual DbSet<PartesPoliciale> PartesPoliciales { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Policia> Policias { get; set; }
        public virtual DbSet<Requisito> Requisitos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesUsuario> RolesUsuarios { get; set; }
        public virtual DbSet<TablaGeneral> TablaGenerals { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
