//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infractores
    {
        public int idInfractor { get; set; }
        public int tipoDeIdentificacion { get; set; }
        public string numeroDeIdentificacion { get; set; }
        public string nacionalidad { get; set; }
        public string nombreCompleto { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string direccionExacta { get; set; }
        public int sexo { get; set; }
        public string correoEletronico { get; set; }
        public string observaciones { get; set; }
        public string profesionUOficio { get; set; }
        public string estatura { get; set; }
        public string tatuajes { get; set; }
        public string nombreDelPadre { get; set; }
        public string nombreDeLaMadre { get; set; }
        public string imagen { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
    }
}
