//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infractores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infractores()
        {
            this.PartesPoliciales = new HashSet<PartesPoliciales>();
        }
    
        public int idInfractor { get; set; }
        public int tipoDeIdentificacion { get; set; }
        public string numeroDeIdentificacion { get; set; }
        public int nacionalidad { get; set; }
        public string nombreCompleto { get; set; }
        public string apodoInfractor { get; set; }
        public string rasgosFisicosInfractor { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string direccionExacta { get; set; }
        public int sexo { get; set; }
        public string correoEletronico { get; set; }
        public string observaciones { get; set; }
        public string profesionUOficio { get; set; }
        public string estatura { get; set; }
        public string tatuajes { get; set; }
        public string nombreDelPadre { get; set; }
        public string nombreDeLaMadre { get; set; }
        public string imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartesPoliciales> PartesPoliciales { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual TablaGeneral TablaGeneral2 { get; set; }
    }
}
