//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartesPoliciale
    {
        public int idPartepolicial { get; set; }
        public string numeroFolio { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime horaSuceso { get; set; }
        public System.DateTime horaConfeccionDocumento { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public int distrito { get; set; }
        public string barrio { get; set; }
        public string direccion { get; set; }
        public int lugarSuceso { get; set; }
        public int idInfractor { get; set; }
        public string edadInfractor { get; set; }
        public int aprehendido { get; set; }
        public Nullable<System.DateTime> horaAprehension { get; set; }
        public Nullable<int> entendido { get; set; }
        public string vestimenta { get; set; }
        public int ofendido1 { get; set; }
        public string edadOfendido1 { get; set; }
        public Nullable<int> ofendido2 { get; set; }
        public string edadOfendido2 { get; set; }
        public Nullable<int> ofendido3 { get; set; }
        public string edadOfendido3 { get; set; }
        public Nullable<int> ofendido4 { get; set; }
        public string edadOfendido4 { get; set; }
        public Nullable<int> ofendido5 { get; set; }
        public string edadOfendido5 { get; set; }
        public Nullable<int> testigo1 { get; set; }
        public Nullable<int> testigo2 { get; set; }
        public string descripcionHechos { get; set; }
        public string diligenciasPoliciales { get; set; }
        public string manifestacionOfendido { get; set; }
        public string manifestacionTestigo { get; set; }
        public int alertador { get; set; }
        public int enteAcargo { get; set; }
        public string movil { get; set; }
        public string movilAsistente { get; set; }
        public int idPoliciaActuante { get; set; }
        public string identificacionOficialAsistente { get; set; }
        public string nombreOficialAsistente { get; set; }
        public string telefonoOficialAsistente { get; set; }
        public int unidadOrigenPoliciaActuante { get; set; }
        public int unidadOrigenPoliciaAsistente { get; set; }
    
        public virtual Infractore Infractore { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual TablaGeneral TablaGeneral2 { get; set; }
        public virtual TablaGeneral TablaGeneral3 { get; set; }
        public virtual TablaGeneral TablaGeneral4 { get; set; }
        public virtual Policia Policia { get; set; }
        public virtual TablaGeneral TablaGeneral5 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TablaGeneral TablaGeneral6 { get; set; }
        public virtual TablaGeneral TablaGeneral7 { get; set; }
    }
}
