//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartesPoliciales
    {
        public int idPartepolicial { get; set; }
        public string numeroFolio { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan horaSuceso { get; set; }
        public System.TimeSpan horaConfeccionDocumento { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public int distrito { get; set; }
        public string barrio { get; set; }
        public string direccion { get; set; }
        public int lugarSuceso { get; set; }
        public int idInfractor { get; set; }
        public string edadInfractor { get; set; }
        public int aprehendido { get; set; }
        public Nullable<System.TimeSpan> horaAprehension { get; set; }
        public Nullable<int> entendido { get; set; }
        public string vestimenta { get; set; }
        public int ofendido1 { get; set; }
        public string edadOfendido1 { get; set; }
        public Nullable<int> ofendido2 { get; set; }
        public string edadOfendido2 { get; set; }
        public Nullable<int> ofendido3 { get; set; }
        public string edadOfendido3 { get; set; }
        public Nullable<int> ofendido4 { get; set; }
        public string edadOfendido4 { get; set; }
        public Nullable<int> ofendido5 { get; set; }
        public string edadOfendido5 { get; set; }
        public Nullable<int> testigo1 { get; set; }
        public Nullable<int> testigo2 { get; set; }
        public string descripcionHechos { get; set; }
        public string diligenciasPoliciales { get; set; }
        public string manifestacionOfendido { get; set; }
        public string manifestacionTestigo { get; set; }
        public int alertador { get; set; }
        public int enteAcargo { get; set; }
        public string movil { get; set; }
        public string movilPoliciaAsistente { get; set; }
        public int idPoliciaActuante { get; set; }
        public int idPoliciaAsistente { get; set; }
        public string unidadOrigenPoliciaActuante { get; set; }
        public string unidadOrigenPoliciaAsiste { get; set; }
    
        public virtual Infractores Infractores { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
        public virtual TablaGeneral TablaGeneral2 { get; set; }
        public virtual TablaGeneral TablaGeneral3 { get; set; }
        public virtual TablaGeneral TablaGeneral4 { get; set; }
        public virtual Policias Policias { get; set; }
        public virtual Policias Policias1 { get; set; }
        public virtual TablaGeneral TablaGeneral5 { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
