//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.ActasDecomiso = new HashSet<ActasDecomiso>();
            this.ActasDeNotificacion = new HashSet<ActasDeNotificacion>();
            this.ActasDeObservacionPolicial = new HashSet<ActasDeObservacionPolicial>();
            this.ActasEntrega = new HashSet<ActasEntrega>();
            this.ActasEntrega1 = new HashSet<ActasEntrega>();
            this.ActasEntregaPorOrdenDe = new HashSet<ActasEntregaPorOrdenDe>();
            this.ActasEntregaPorOrdenDe1 = new HashSet<ActasEntregaPorOrdenDe>();
            this.ActasNotificacionVendedorAmbulante = new HashSet<ActasNotificacionVendedorAmbulante>();
            this.PartesPoliciales = new HashSet<PartesPoliciales>();
        }
    
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public int tipoIdentificacion { get; set; }
        public string identificacion { get; set; }
        public Nullable<int> sexo { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> nacionalidad { get; set; }
        public string instalaciones { get; set; }
        public string direccionPersona { get; set; }
        public string telefonoHabitacion { get; set; }
        public string telefonoTrabajo { get; set; }
        public string telefonoCelular { get; set; }
        public string profesion { get; set; }
        public string correoElectronicoPersona { get; set; }
        public string lugarTrabajoPersona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasDecomiso> ActasDecomiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasDeNotificacion> ActasDeNotificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasDeObservacionPolicial> ActasDeObservacionPolicial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasEntrega> ActasEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasEntrega> ActasEntrega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasEntregaPorOrdenDe> ActasEntregaPorOrdenDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasEntregaPorOrdenDe> ActasEntregaPorOrdenDe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasNotificacionVendedorAmbulante> ActasNotificacionVendedorAmbulante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartesPoliciales> PartesPoliciales { get; set; }
        public virtual TablaGeneral TablaGeneral { get; set; }
    }
}
