//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policias
    {
        public int idPolicia { get; set; }
        public string cedula { get; set; }
        public int tipoCedula { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string correoElectronico { get; set; }
        public string direccion { get; set; }
        public string telefonoCelular { get; set; }
        public string telefonoCasa { get; set; }
        public string contactoEmergencia { get; set; }
        public string telefonoEmergencia { get; set; }
        public int estado { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual TablaGeneral TablaGeneral1 { get; set; }
    }
}
